# Generated by Django 3.0.7 on 2020-08-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
