# Generated by Django 3.0.7 on 2020-08-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200728_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='guard',
        ),
    ]
