# Generated by Django 3.0.7 on 2020-08-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_index_together_recipient_unread'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
